### ISSUE TITLE
大神，请问这个怎么食用啊？

### ISSUE THREAD

**Issue by justincnn** [PinghuaZhuang/automatic#1]
### What problem

Description of the problem, as detailed as possible.

### Environment

- Mobile: MI6
- System: Android7.1.1
- Browser：Chrome61
- jslib-base version: 0.2.0
- some other information

### Online demo

Please provide online demo if possible.

### Other

some other information.

**Comment by PinghuaZhuang** [comment]
原理是使用 `puppeteer` 打开浏览器进行签到. 但是服务器有访问限制. 所依 `git action `.circleci` 这些现在用不了.  只能跑在自己电脑上.
